### ISSUE TITLE
Test suite does not deference verificationMethod

### ISSUE THREAD

**Issue by filip26** [w3c-ccg/di-ed25519-test-suite#23]
Hi,
a test on proofValue length fails in 

```bash
    ❌ "proofValue" field when decoded to raw bytes, MUST be 64 bytes in length if the associated public key is 32 bytes or 114 bytes in length if the public key is 57 bytes.
    Error: "publicKeyMultibase" has invalid header bytes: "vc.apicatalog.com/key/test.json".
at new Ed25519VerificationKey2020 (node_modules/@digitalbazaar/ed25519-verification-key-2020/lib/Ed25519VerificationKey2020.js:54:13)
at Function.fromFingerprint (node_modules/@digitalbazaar/ed25519-verification-key-2020/lib/Ed25519VerificationKey2020.js:204:12)
at DidKeyDriver.get (node_modules/@digitalbazaar/did-method-key/lib/DidKeyDriver.js:140:44)
at getPublicKeyBytes (tests/helpers.js:44:37)
at Context.<anonymous> (tests/10-create.js:104:35)
```
when verification method is not DID key. e.g.

```json
"verificationMethod": "https://vc.apicatalog.com/key/test.json"
```

The suite just strips `https://` from the URL and treats the URL as DID key.

**Comment by msporny** [comment]
The test suite is set up to use did:key as the verification method (we can't support arbitrary verification methods -- did:key is the simplest one we can use). The test suite should be checking to make sure the verificationMethod is a did:key before trying to do something w/ it.

**Comment by aljones15** [comment]
@msporny Perhaps we should require vendors to provide a did resolver for their did key in the future? That way they can use did methods we don't have implementations of.
