### ISSUE TITLE
Ed25519Signature2020 - Issuer: proofValue length test always fails

### ISSUE THREAD

**Issue by filip26** [w3c-ccg/di-ed25519-test-suite#24]
Hi,
not sure where is the issue, but the proofValue length test always fails to me with

```bash
  ❌ "proofValue" field when decoded to raw bytes, MUST be 64 bytes in length if the associated public key is 32 bytes or 114 bytes in length if the public key is 57 bytes.
  TypeError: Cannot read properties of undefined (reading 'length')
at IdDecoder.decode (node_modules/bnid/main.js:280:44)
at getPublicKeyBytes (tests/helpers.js:47:35)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Context.<anonymous> (tests/10-create.js:109:29)
```
Please note reading `length` of undefined error caused by `helpres.js:45`

```javascript
42: const getPublicKeyBytes = async ({did}) => {
44:  const didDoc = await didKeyDriver.get({did});
45:  const multiCodecBytes = decoder.decode(didDoc.publicKeyMultibase);
```
The `didDoc` does not have `publicKeyMultibase` property at top level and `decoder.decode` fails with reading of undefined.

Example DID key causing it:
```
did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y
```

**Comment by aljones15** [comment]
Ok so the issue here is that the verificationMethod is the `didDoc` itself and not the `verificationMethod` itself:
```js
{
  "issuedVc": {
    "id": "urn:uuid:24e13b94-cc63-49db-88ee-6a6792db246c",
    "type": [
      "VerifiableCredential",
      "TestCredential"
    ],
    "issuer": "did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y",
    "issuanceDate": "2020-03-16T22:37:26.544Z",
    "credentialSubject": {
      "id": "did:key:z6MktKwz7Ge1Yxzr4JHavN33wiwa8y81QdcMRLXQsrH9T53b"
    },
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "proof": {
      "type": "Ed25519Signature2020",
      "verificationMethod": "did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y",
      "created": "2022-06-29T17:34:20Z",
      "proofPurpose": "assertionMethod",
      "proofValue": "z4qfLrQgRNHReh2VQiZ7BDjXb8caSA8cffUXvictqcgki6BpSDq5gitNa31q1tHxTVYPkYjmRzTs2jh7UosCGLShd"
    }
  },
  "name": "apicatalog.com"
}
```


```js
> driver.get({did: 'did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y'}).then(console.log)
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 2639,
  [Symbol(trigger_async_id_symbol)]: 2634,
  [Symbol(destroyed)]: { destroyed: false }
}
> {
  '@context': [
    'https://www.w3.org/ns/did/v1',
    'https://w3id.org/security/suites/ed25519-2020/v1',
    'https://w3id.org/security/suites/x25519-2020/v1'
  ],
  id: 'did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y',
  verificationMethod: [
    {
      id: 'did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y#z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y',
      type: 'Ed25519VerificationKey2020',
      controller: 'did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y',
      publicKeyMultibase: 'z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y'
    }
  ],
  authentication: [
    'did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y#z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y'
  ],
  assertionMethod: [
    'did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y#z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y'
  ],
  capabilityDelegation: [
    'did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y#z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y'
  ],
  capabilityInvocation: [
    'did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y#z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y'
  ],
  keyAgreement: [
    {
      id: 'did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y#z6LSs7VdvHqinnRj6x66hWK5S7jnopFkrqopYCW5KcDXVtN1',
      type: 'X25519KeyAgreementKey2020',
      controller: 'did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y',
      publicKeyMultibase: 'z6LSs7VdvHqinnRj6x66hWK5S7jnopFkrqopYCW5KcDXVtN1'
    }
  ]
}
```

vs

```js
{
  "issuedVc": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "id": "urn:uuid:a6b0183d-f3d6-432a-8ba4-77e6af2c72af",
    "type": [
      "VerifiableCredential",
      "TestCredential"
    ],
    "issuer": "did:key:z6MkkyNu8RUzvTMCkbw7HyNGPzuExz7VMbeoMtRuu9o4kGdw",
    "issuanceDate": "2020-03-16T22:37:26.544Z",
    "credentialSubject": {
      "id": "did:key:z6MktKwz7Ge1Yxzr4JHavN33wiwa8y81QdcMRLXQsrH9T53b"
    },
    "proof": {
      "type": "Ed25519Signature2020",
      "created": "2022-06-29T17:34:19Z",
      "verificationMethod": "did:key:z6MkkyNu8RUzvTMCkbw7HyNGPzuExz7VMbeoMtRuu9o4kGdw#z6MkkyNu8RUzvTMCkbw7HyNGPzuExz7VMbeoMtRuu9o4kGdw",
      "proofPurpose": "assertionMethod",
      "proofValue": "z9nmvuueQpgD5jSWFSzq4HgX7MpXw9Bc2WvcKFhyqH5qmWepJuz6xr3jSmWz7KUMdw6uLAU2cpLwuRAndZi6sLMQ"
    }
  },
  "name": "Digital Bazaar"
}
```

```js
> driver.get({did: 'did:key:z6MkkyNu8RUzvTMCkbw7HyNGPzuExz7VMbeoMtRuu9o4kGdw#z6MkkyNu8RUzvTMCkbw7HyNGPzuExz7VMbeoMtRuu9o4kGdw'}).then(console.log)
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 2959,
  [Symbol(trigger_async_id_symbol)]: 2954,
  [Symbol(destroyed)]: { destroyed: false }
}
> {
  '@context': 'https://w3id.org/security/suites/ed25519-2020/v1',
  id: 'did:key:z6MkkyNu8RUzvTMCkbw7HyNGPzuExz7VMbeoMtRuu9o4kGdw#z6MkkyNu8RUzvTMCkbw7HyNGPzuExz7VMbeoMtRuu9o4kGdw',
  type: 'Ed25519VerificationKey2020',
  controller: 'did:key:z6MkkyNu8RUzvTMCkbw7HyNGPzuExz7VMbeoMtRuu9o4kGdw',
  publicKeyMultibase: 'z6MkkyNu8RUzvTMCkbw7HyNGPzuExz7VMbeoMtRuu9o4kGdw'
}
```

**Comment by filip26** [comment]
@aljones15 great, thank you! my bad.
